<h3 style="color:#C0C0C0;text-align:center;font-size: smaller;">Applied Machine Learning and Data Mining - U26538</h3>

<br>
<h1 style="color:#800080;text-align:center;"> Practical Exercise (7)</h1>
<h2 style="color:#800080;text-align:center;">Advanced DataFrame Functions</h2>

From moodle/ datasets, download the bank dataset and upload it to your jupyter directory. Read DataSet Information to understand the data https://archive.ics.uci.edu/ml/datasets/Bank+Marketing.

Create a new Juypter notebook called practex7.

<ol>
<li>import the required libraries.</li>
<li>Read the dataset.</li>
<li>Display the data type for the attributes in the dataset.</li>
<li>Change the data type for the <i>balance</i> attribute from int to float.</li>
<li>Using the locate function, display row number 60. (the output should be shown as a dataframe).</li>
<li>Add a new row in the dataframe using dataframe <code>.append()</code> and fill in all the attributes.</li>
<li>Rename the attribute job to job types.</li>
<li>Delete row numbers 7, 13, 20, and 28.</li>
<li>Get the number of <i>poutcome</i> for each attribute using the group by function.</li>
</ol>