<h3 style="color:#C0C0C0;text-align:center;font-size: smaller;">Applied Machine Learning and Data Mining - U26538</h3>

<br>
<h1 style="color:#800080;text-align:center;"> Practical Worksheet (21)</h1>
<h2 style="color:#800080;text-align:center;">Association Rules (Apriori )</h2>

<h3 b> Introduction </h3>

In the following practical worksheet, you will learn how to apply association rules using the Apriori algorithm. If you have any questions please ask for assistance during the session and you can also email me if you have any further questions <u> alaa.mohasseb@port.ac.uk</u>.

<b><u>Example 1 - Retail Dataset</u></b>

Download the Dataset from Moodle

<i>Description:</i>  each row of the dataset represents items that were purchased together on the same day at the same store. The dataset is a sparse dataset as a relatively high percentage of data is NA or NaN or equivalent.

<u>Download Apriori Algorithm</u>

In [1]:
!pip install apriori

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting apriori
  Downloading apriori-1.0.0.tar.gz (1.8 kB)
Building wheels for collected packages: apriori
  Building wheel for apriori (setup.py) ... done
  Created wheel for apriori: filename=apriori-1.0.0-py2-none-any.whl size=3153 sha256=4766ebe76184169764a9013f74b5e8cb409b60f42aae8fd85fffe30c805d4bed
  Stored in directory: /Users/alaamohasseb/Library/Caches/pip/wheels/f3/92/ac/df599ccd708a7ffefee42d4685821a9156b0341dd55a8ad970
Successfully built apriori
Installing collected packages: apriori
Successfully installed apriori-1.0.0

<u>Import the Libraries</u>

In a new Jupyter Notebook (practWeek21), load the following libraries:

In [2]:
import numpy as np        # used for multidimensional array
import pandas as pd       # used for import the dataset
import seaborn as sns
import matplotlib.pyplot as plt   # used for plotting the Graph
%matplotlib inline
from apyori import apriori # association rule

<u>Read External Data</u> (Retail Dataset)
<ul>
<li>Download the dataset from your moodle page.</li>
<li>Upload the dataset to your Jupyter dashboard.</li>
<li>To read an external data (csv file) use the following command:</li>
</ul>

In [4]:
# import dataset
df = pd.read_csv('retail_dataset.csv', sep=',')
df.head()

        0       1     2       3       4       5       6
0   Bread    Wine  Eggs    Meat  Cheese  Pencil  Diaper
1   Bread  Cheese  Meat  Diaper    Wine    Milk  Pencil
2  Cheese    Meat  Eggs    Milk    Wine     NaN     NaN
3  Cheese    Meat  Eggs    Milk    Wine     NaN     NaN
4    Meat  Pencil  Wine     NaN     NaN     NaN     NaN

<u>Data understanding</u>

In order to understand the dataset, analysis should be done and some information needs to be explored.

use the <code>.describe()</code> to display the statistical properties of the data

In [5]:
df.describe()

            0      1     2     3     4       5      6
count     315    285   245   187   133      71     41
unique      9      9     9     9     9       9      9
top     Bread  Bagel  Eggs  Milk  Wine  Pencil  Bread
freq       74     47    52    45    36      13     11

Print the data as a dataframe

In [6]:
df.head()

        0       1     2       3       4       5       6
0   Bread    Wine  Eggs    Meat  Cheese  Pencil  Diaper
1   Bread  Cheese  Meat  Diaper    Wine    Milk  Pencil
2  Cheese    Meat  Eggs    Milk    Wine     NaN     NaN
3  Cheese    Meat  Eggs    Milk    Wine     NaN     NaN
4    Meat  Pencil  Wine     NaN     NaN     NaN     NaN

Display unique Values

In [7]:
items = (df['0'].unique())
items

array(['Bread', 'Cheese', 'Meat', 'Eggs', 'Wine', 'Bagel', 'Pencil',
       'Diaper', 'Milk'], dtype=object)

<u>Data Preprocessing</u>

<i>Convert Data</i>

- To convert the pandas dataframe into a list of lists.

- The Apriori library we are going to use requires the dataset to be in the form of a list of lists, where the whole dataset is a big list and each transaction in the dataset is an inner list within the outer big list. Currently, the data is in the form of a pandas dataframe.

<i>Note:</i> 

- 315 in range (0, 315) is the number of records in the dataset.
- 7 in range (0,7) is the number of columns.
- You can use <code>df.shape</code> to display these information.

In [8]:
records = []
for i in range(0, 315):
    records.append([str(df.values[i,j]) for j in range(0, 7)])

<u>Applying Apriori Algorithm</u>

- min_support: The minimum support of relations (float)
- min_confidence: The minimum confidence of relations (float)
- min_lift: The minimum lift of relations (float)
- min_length: The minimum number of items in a rule
- max_length: The maximum number of items in a rule

- The optimum values for min_support,min_confidence and  min_lift arguments can be set by trying out different values and checking the association rules whether the arguments produced a valid association between items or not.

In [10]:
# association rule apriori
association_rules = apriori(records, min_support=0.0045, min_confidence=0.7, min_lift=3, min_length=2)
association_results = list(association_rules)

<u>Display the Results</u>

In [11]:
# print the total number of rules mined by the apriori class
print(len(association_results))

6

<u>Print the Rules</u>

In [13]:
# print the first item in the association rules
print(association_results[0])

RelationRecord(items=frozenset(['Cheese', 'Meat', 'Eggs', 'nan', 'Bagel', 'Diaper', 'Bread']), support=0.006349206349206349, ordered_statistics=[OrderedStatistic(items_base=frozenset(['Bagel', 'Eggs', 'nan', 'Diaper', 'Bread']), items_add=frozenset(['Cheese', 'Meat']), confidence=1.0, lift=3.0882352941176467)])

<u>Print Detailed Rules</u>

In [14]:
# print the rules, the support, the confidence, and lift for each rule
for item in association_results:

    # first index of the inner list
    # Contains base item and add item
    pair = item[0] 
    items = [x for x in pair]
    print("Rule: " + items[0] + " -> " + items[1])

    #second index of the inner list
    print("Support: " + str(item[1]))

    #third index of the list located at 0th
    #of the third index of the inner list

    print("Confidence: " + str(item[2][0][2]))
    print("Lift: " + str(item[2][0][3]))
    print("=====================================")

Rule: Cheese -> Meat
Support: 0.00634920634921
Confidence: 1.0
Lift: 3.08823529412
=====================================
Rule: Cheese -> Meat
Support: 0.00634920634921
Confidence: 1.0
Lift: 3.57954545455
=====================================
Rule: Pencil -> Meat
Support: 0.00634920634921
Confidence: 1.0
Lift: 3.57954545455
=====================================
Rule: Cheese -> Meat
Support: 0.00634920634921
Confidence: 1.0
Lift: 4.2
=====================================
Rule: Cheese -> Meat
Support: 0.00952380952381
Confidence: 1.0
Lift: 4.09090909091
=====================================
Rule: Pencil -> Meat
Support: 0.00634920634921
Confidence: 1.0
Lift: 5.0
=====================================

<b><u>Example 2 - Market basket Dataset </u></b>

Download the Dataset from Moodle

<i>Description:</i> This dataset represents information about customers buying different grocery items.

<u>Import/read the dataset</u>

In [16]:
# import dataset
df = pd.read_csv('market_basket.csv', header=None)
num_records =len(df)
print(num_records)

7501

In [17]:
# display the first few rows of the dataset
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<u>Dataset Description</u>

In [18]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
count,7501,5747,4389,3345,2529,1864,1369,981,654,395,256,154,87,47,25,8,4,4,3,1
unique,115,117,115,114,110,106,102,98,88,80,66,50,43,28,19,8,3,3,3,1
top,mineral water,mineral water,mineral water,mineral water,green tea,french fries,green tea,green tea,green tea,green tea,low fat yogurt,green tea,green tea,green tea,magazines,salmon,frozen smoothie,protein bar,mayonnaise,olive oil
freq,577,484,375,201,153,107,96,67,57,31,22,15,8,4,3,1,2,2,1,1

<u>Display shape</u>

In [20]:
df.shape

(7501, 20)

<u>Data preprocessing</u>

Convert Data

In [22]:
records = []
for i in range(num_records):
    records.append([str(df.values[i,j]) for j in range(0, 20)])

<u>Applying Apriori Algorithm</u>

In [23]:
# association rule apriori
association_rules = apriori(records, min_support=0.006, min_confidence=0.2, min_lift=3, min_length=2)
association_results = list(association_rules)

<u>Display the Results</u>

In [24]:
# print the total number of rules mined by the apriori class
print(len(association_results))

16

<u>Print the rules</u>

In [25]:
# print the first item in the association rules
print(association_results[0])

RelationRecord(items=frozenset(['herb & pepper', 'ground beef']), support=0.015997866951073192, ordered_statistics=[OrderedStatistic(items_base=frozenset(['herb & pepper']), items_add=frozenset(['ground beef']), confidence=0.3234501347708895, lift=3.2919938411349285)])

<u>Print Detailed Rules</u>

In [26]:
# another way to print and display the rule, the support, the confidence, and lift for each rule
results = []
for item in association_results:

    # first index of the inner list
    # Contains base item and add item
    pair = item[0] 
    items = [x for x in pair]
    value0= str(items[0])
    value1= str(items[1])
    

    #second index of the inner list
    value2=str(item[1])[:7]

    #third index of the list located at 0th
    #of the third index of the inner list
    value3 =str(item[2][0][2])[:7]
    value4 =str(item[2][0][3])[:7]
    
    rows=(value0, value1, value2, value3, value4)
    results.append(rows)
    
    labels =['Title 1', 'Title 2', 'Support', 'Confidence', 'Lift']
    df= pd.DataFrame.from_records(results, columns = labels)
    print(df)
    print("=====================================")

         Title 1      Title 2  Support Confidence     Lift
0  herb & pepper  ground beef  0.01599    0.32345  3.29199
=====================================
         Title 1            Title 2  Support Confidence     Lift
0  herb & pepper        ground beef  0.01599    0.32345  3.29199
1      olive oil  whole wheat pasta  0.00799    0.27149  4.12241
=====================================
             Title 1            Title 2  Support Confidence     Lift
0      herb & pepper        ground beef  0.01599    0.32345  3.29199
1          olive oil  whole wheat pasta  0.00799    0.27149  4.12241
2  frozen vegetables          spaghetti  0.00866    0.31100  3.16532
=====================================
             Title 1            Title 2  Support Confidence     Lift
0      herb & pepper        ground beef  0.01599    0.32345  3.29199
1          olive oil  whole wheat pasta  0.00799    0.27149  4.12241
2  frozen vegetables          spaghetti  0.00866    0.31100  3.16532
3      mineral water  frozen vegetables  0.00719    0.30508  3.20061
=====================================
             Title 1            Title 2  Support Confidence     Lift
0      herb & pepper        ground beef  0.01599    0.32345  3.29199
1          olive oil  whole wheat pasta  0.00799    0.27149  4.12241
2  frozen vegetables          spaghetti  0.00866    0.31100  3.16532
3      mineral water  frozen vegetables  0.00719    0.30508  3.20061
4  frozen vegetables          spaghetti  0.00666    0.23923  3.49804
=====================================
             Title 1            Title 2  Support Confidence     Lift
0      herb & pepper        ground beef  0.01599    0.32345  3.29199
1          olive oil  whole wheat pasta  0.00799    0.27149  4.12241
2  frozen vegetables          spaghetti  0.00866    0.31100  3.16532
3      mineral water  frozen vegetables  0.00719    0.30508  3.20061
4  frozen vegetables          spaghetti  0.00666    0.23923  3.49804
5      mineral water      herb & pepper  0.00666    0.39062  3.97568
=====================================
             Title 1            Title 2  Support Confidence     Lift
0      herb & pepper        ground beef  0.01599    0.32345  3.29199
1          olive oil  whole wheat pasta  0.00799    0.27149  4.12241
2  frozen vegetables          spaghetti  0.00866    0.31100  3.16532
3      mineral water  frozen vegetables  0.00719    0.30508  3.20061
4  frozen vegetables          spaghetti  0.00666    0.23923  3.49804
5      mineral water      herb & pepper  0.00666    0.39062  3.97568
6                nan      herb & pepper  0.01599    0.32345  3.29199
=====================================
             Title 1            Title 2  Support Confidence     Lift
0      herb & pepper        ground beef  0.01599    0.32345  3.29199
1          olive oil  whole wheat pasta  0.00799    0.27149  4.12241
2  frozen vegetables          spaghetti  0.00866    0.31100  3.16532
3      mineral water  frozen vegetables  0.00719    0.30508  3.20061
4  frozen vegetables          spaghetti  0.00666    0.23923  3.49804
5      mineral water      herb & pepper  0.00666    0.39062  3.97568
6                nan      herb & pepper  0.01599    0.32345  3.29199
7          spaghetti      herb & pepper  0.00639    0.39344  4.00435
=====================================
             Title 1            Title 2  Support Confidence     Lift
0      herb & pepper        ground beef  0.01599    0.32345  3.29199
1          olive oil  whole wheat pasta  0.00799    0.27149  4.12241
2  frozen vegetables          spaghetti  0.00866    0.31100  3.16532
3      mineral water  frozen vegetables  0.00719    0.30508  3.20061
4  frozen vegetables          spaghetti  0.00666    0.23923  3.49804
5      mineral water      herb & pepper  0.00666    0.39062  3.97568
6                nan      herb & pepper  0.01599    0.32345  3.29199
7          spaghetti      herb & pepper  0.00639    0.39344  4.00435
8          olive oil          spaghetti  0.00719    0.20300  3.08250
=====================================
             Title 1            Title 2  Support Confidence     Lift
0      herb & pepper        ground beef  0.01599    0.32345  3.29199
1          olive oil  whole wheat pasta  0.00799    0.27149  4.12241
2  frozen vegetables          spaghetti  0.00866    0.31100  3.16532
3      mineral water  frozen vegetables  0.00719    0.30508  3.20061
4  frozen vegetables          spaghetti  0.00666    0.23923  3.49804
5      mineral water      herb & pepper  0.00666    0.39062  3.97568
6                nan      herb & pepper  0.01599    0.32345  3.29199
7          spaghetti      herb & pepper  0.00639    0.39344  4.00435
8          olive oil          spaghetti  0.00719    0.20300  3.08250
9          olive oil  whole wheat pasta  0.00799    0.27149  4.13077
=====================================
              Title 1            Title 2  Support Confidence     Lift
0       herb & pepper        ground beef  0.01599    0.32345  3.29199
1           olive oil  whole wheat pasta  0.00799    0.27149  4.12241
2   frozen vegetables          spaghetti  0.00866    0.31100  3.16532
3       mineral water  frozen vegetables  0.00719    0.30508  3.20061
4   frozen vegetables          spaghetti  0.00666    0.23923  3.49804
5       mineral water      herb & pepper  0.00666    0.39062  3.97568
6                 nan      herb & pepper  0.01599    0.32345  3.29199
7           spaghetti      herb & pepper  0.00639    0.39344  4.00435
8           olive oil          spaghetti  0.00719    0.20300  3.08250
9           olive oil  whole wheat pasta  0.00799    0.27149  4.13077
10          spaghetti  frozen vegetables  0.00866    0.31100  3.16532
=====================================
              Title 1            Title 2  Support Confidence     Lift
0       herb & pepper        ground beef  0.01599    0.32345  3.29199
1           olive oil  whole wheat pasta  0.00799    0.27149  4.12241
2   frozen vegetables          spaghetti  0.00866    0.31100  3.16532
3       mineral water  frozen vegetables  0.00719    0.30508  3.20061
4   frozen vegetables          spaghetti  0.00666    0.23923  3.49804
5       mineral water      herb & pepper  0.00666    0.39062  3.97568
6                 nan      herb & pepper  0.01599    0.32345  3.29199
7           spaghetti      herb & pepper  0.00639    0.39344  4.00435
8           olive oil          spaghetti  0.00719    0.20300  3.08250
9           olive oil  whole wheat pasta  0.00799    0.27149  4.13077
10          spaghetti  frozen vegetables  0.00866    0.31100  3.16532
11      mineral water  frozen vegetables  0.00719    0.30508  3.20061
=====================================
              Title 1            Title 2  Support Confidence     Lift
0       herb & pepper        ground beef  0.01599    0.32345  3.29199
1           olive oil  whole wheat pasta  0.00799    0.27149  4.12241
2   frozen vegetables          spaghetti  0.00866    0.31100  3.16532
3       mineral water  frozen vegetables  0.00719    0.30508  3.20061
4   frozen vegetables          spaghetti  0.00666    0.23923  3.49804
5       mineral water      herb & pepper  0.00666    0.39062  3.97568
6                 nan      herb & pepper  0.01599    0.32345  3.29199
7           spaghetti      herb & pepper  0.00639    0.39344  4.00435
8           olive oil          spaghetti  0.00719    0.20300  3.08250
9           olive oil  whole wheat pasta  0.00799    0.27149  4.13077
10          spaghetti  frozen vegetables  0.00866    0.31100  3.16532
11      mineral water  frozen vegetables  0.00719    0.30508  3.20061
12          spaghetti  frozen vegetables  0.00666    0.23923  3.49804
=====================================
              Title 1            Title 2  Support Confidence     Lift
0       herb & pepper        ground beef  0.01599    0.32345  3.29199
1           olive oil  whole wheat pasta  0.00799    0.27149  4.12241
2   frozen vegetables          spaghetti  0.00866    0.31100  3.16532
3       mineral water  frozen vegetables  0.00719    0.30508  3.20061
4   frozen vegetables          spaghetti  0.00666    0.23923  3.49804
5       mineral water      herb & pepper  0.00666    0.39062  3.97568
6                 nan      herb & pepper  0.01599    0.32345  3.29199
7           spaghetti      herb & pepper  0.00639    0.39344  4.00435
8           olive oil          spaghetti  0.00719    0.20300  3.08250
9           olive oil  whole wheat pasta  0.00799    0.27149  4.13077
10          spaghetti  frozen vegetables  0.00866    0.31100  3.16532
11      mineral water  frozen vegetables  0.00719    0.30508  3.20061
12          spaghetti  frozen vegetables  0.00666    0.23923  3.49804
13                nan      mineral water  0.00666    0.39062  3.97568
=====================================
              Title 1            Title 2  Support Confidence     Lift
0       herb & pepper        ground beef  0.01599    0.32345  3.29199
1           olive oil  whole wheat pasta  0.00799    0.27149  4.12241
2   frozen vegetables          spaghetti  0.00866    0.31100  3.16532
3       mineral water  frozen vegetables  0.00719    0.30508  3.20061
4   frozen vegetables          spaghetti  0.00666    0.23923  3.49804
5       mineral water      herb & pepper  0.00666    0.39062  3.97568
6                 nan      herb & pepper  0.01599    0.32345  3.29199
7           spaghetti      herb & pepper  0.00639    0.39344  4.00435
8           olive oil          spaghetti  0.00719    0.20300  3.08250
9           olive oil  whole wheat pasta  0.00799    0.27149  4.13077
10          spaghetti  frozen vegetables  0.00866    0.31100  3.16532
11      mineral water  frozen vegetables  0.00719    0.30508  3.20061
12          spaghetti  frozen vegetables  0.00666    0.23923  3.49804
13                nan      mineral water  0.00666    0.39062  3.97568
14                nan          spaghetti  0.00639    0.39344  4.00435
=====================================
              Title 1            Title 2  Support Confidence     Lift
0       herb & pepper        ground beef  0.01599    0.32345  3.29199
1           olive oil  whole wheat pasta  0.00799    0.27149  4.12241
2   frozen vegetables          spaghetti  0.00866    0.31100  3.16532
3       mineral water  frozen vegetables  0.00719    0.30508  3.20061
4   frozen vegetables          spaghetti  0.00666    0.23923  3.49804
5       mineral water      herb & pepper  0.00666    0.39062  3.97568
6                 nan      herb & pepper  0.01599    0.32345  3.29199
7           spaghetti      herb & pepper  0.00639    0.39344  4.00435
8           olive oil          spaghetti  0.00719    0.20300  3.08250
9           olive oil  whole wheat pasta  0.00799    0.27149  4.13077
10          spaghetti  frozen vegetables  0.00866    0.31100  3.16532
11      mineral water  frozen vegetables  0.00719    0.30508  3.20061
12          spaghetti  frozen vegetables  0.00666    0.23923  3.49804
13                nan      mineral water  0.00666    0.39062  3.97568
14                nan          spaghetti  0.00639    0.39344  4.00435
15          olive oil          spaghetti  0.00719    0.20300  3.08876
=====================================

<b><u>Example 3 - Music Dataset</b></u> 

Download the Dataset from Moodle

<i>Description:</i> Music data collected from a website last.fm. The dataset contains anonymized user data from the website

<u>Import/read the dataset</u>

In [27]:
# import dataset
df = pd.read_csv('Music.csv')

In [28]:
df.head()

   user                   artist sex  country
0     1    red hot chili peppers   f  Germany
1     1  the black dahlia murder   f  Germany
2     1                goldfrapp   f  Germany
3     1         dropkick murphys   f  Germany
4     1                 le tigre   f  Germany

<u>Print data information</u>

In [29]:
df.describe()

                user
count  289955.000000
mean     9852.460447
std      5692.355041
min         1.000000
25%      4935.000000
50%      9838.000000
75%     14769.000000
max     19718.000000

<u>Print the shape of the data</u>

In [30]:
df.shape

(289955, 4)

<u>Attributes Selection</u>

In this example the user and artists column will be used

In [31]:
df = df[['user','artist']]
df

         user                   artist
0           1    red hot chili peppers
1           1  the black dahlia murder
2           1                goldfrapp
3           1         dropkick murphys
4           1                 le tigre
5           1               schandmaul
6           1                    edguy
7           1             jack johnson
8           1                eluveitie
9           1              the killers
10          1             judas priest
11          1               rob zombie
12          1               john mayer
13          1                  the who
14          1               guano apes
15          1       the rolling stones
16          3         devendra banhart
17          3         boards of canada
18          3                cocorosie
19          3               aphex twin
20          3        animal collective
21          3               atmosphere
22          3            joanna newsom
23          3                      air
24          3               portishead
25          3           massive attack
26          3      broken social scene
27          3              arcade fire
28          3                    plaid
29          3               prefuse 73
...       ...                      ...
289925  19718                   beirut
289926  19718              of montreal
289927  19718               black flag
289928  19718    the new pornographers
289929  19718          yeah yeah yeahs
289930  19718                the shins
289931  19718               neil young
289932  19718        the white stripes
289933  19718             the national
289934  19718              the beatles
289935  19718           sufjan stevens
289936  19718          crystal castles
289937  19718           regina spektor
289938  19718   the velvet underground
289939  19718             joy division
289940  19718           the distillers
289941  19718                   metric
289942  19718     peter bjorn and john
289943  19718                  ramones
289944  19718                the kinks
289945  19718              david bowie
289946  19718                     mgmt
289947  19718            cold war kids
289948  19718            fleetwood mac
289949  19718              arcade fire
289950  19718                bob dylan
289951  19718                   pixies
289952  19718                the clash
289953  19718     a tribe called quest
289954  19718                radiohead

[289955 rows x 2 columns]

<u>Data Preprocessing</u>

Drop Duplicate Data

In [33]:
df = df.drop_duplicates()
df.shape

(289953, 2)

Transform the Dataset into list

In [34]:
records = []
for i in df['user'].unique():
    records.append(list(df[df['user'] == i]['artist'].values))

<u>Print type</u>

In [35]:
print(type(records))

<type 'list'>

<u>Applying Apriori Algorithm</u>

In [36]:
# association rule apriori
association_rules = apriori(records, min_support=0.01, min_confidence=0.4, min_lift=3, min_length=2)
association_results = list(association_rules)

<u>View the Results</u>

In [37]:
print("There are {} Relation derived.".format(len(association_results)))

There are 91 Relation derived.

<u>Print the Rules</u>

In [38]:
#print all the rules
for i in range(0, len(association_results)):
    print(association_results[i][0])

frozenset(['a perfect circle', 'tool'])
frozenset(['arctic monkeys', 'kaiser chiefs'])
frozenset(['rihanna', 'beyonc\xc3\x83\xc2\xa9'])
frozenset(['black sabbath', 'metallica'])
frozenset(['sum 41', 'blink-182'])
frozenset(['breaking benjamin', 'linkin park'])
frozenset(['death cab for cutie', 'bright eyes'])
frozenset(['death cab for cutie', 'broken social scene'])
frozenset(['radiohead', 'broken social scene'])
frozenset(['children of bodom', 'in flames'])
frozenset(['keane', 'coldplay'])
frozenset(['coldplay', 'snow patrol'])
frozenset(['coldplay', 'the fray'])
frozenset(['travis', 'coldplay'])
frozenset(['daft punk', 'justice'])
frozenset(['death cab for cutie', 'the decemberists'])
frozenset(['death cab for cutie', 'the postal service'])
frozenset(['death cab for cutie', 'the shins'])
frozenset(['led zeppelin', 'deep purple'])
frozenset(['metallica', 'dream theater'])
frozenset(['panic at the disco', 'fall out boy'])
frozenset(['kaiser chiefs', 'franz ferdinand'])
frozenset(['linkin park', 'good charlotte'])
frozenset(['guns n roses', 'metallica'])
frozenset(['iron maiden', 'judas priest'])
frozenset(['iron maiden', 'megadeth'])
frozenset(['iron maiden', 'metallica'])
frozenset(['kanye west', 'jay-z'])
frozenset(['nas', 'jay-z'])
frozenset(['led zeppelin', 'jimi hendrix'])
frozenset(['metallica', 'judas priest'])
frozenset(['kaiser chiefs', 'the killers'])
frozenset(['nas', 'kanye west'])
frozenset(['kanye west', 't.i.'])
frozenset(['keane', 'the killers'])
frozenset(['ko\xc3\x90\xc2\xafn', 'system of a down'])
frozenset(['madonna', 'kylie minogue'])
frozenset(['led zeppelin', 'pink floyd'])
frozenset(['limp bizkit', 'linkin park'])
frozenset(['linkin park', 'papa roach'])
frozenset(['metallica', 'megadeth'])
frozenset(['mot\xc3\x83\xc2\xb6rhead', 'metallica'])
frozenset(['pantera', 'metallica'])
frozenset(['slayer', 'metallica'])
frozenset(['morrissey', 'the smiths'])
frozenset(['sonata arctica', 'nightwish'])
frozenset(['rihanna', 'the pussycat dolls'])
frozenset(['slipknot', 'system of a down'])
frozenset(['arctic monkeys', 'coldplay', 'muse'])
frozenset(['arctic monkeys', 'radiohead', 'coldplay'])
frozenset(['arctic monkeys', 'coldplay', 'the killers'])
frozenset(['arctic monkeys', 'radiohead', 'muse'])
frozenset(['arctic monkeys', 'the killers', 'muse'])
frozenset(['beck', 'radiohead', 'the beatles'])
frozenset(['coldplay', 'the killers', 'bloc party'])
frozenset(['pink floyd', 'the beatles', 'bob dylan'])
frozenset(['radiohead', 'the beatles', 'bob dylan'])
frozenset(['the rolling stones', 'the beatles', 'bob dylan'])
frozenset(['death cab for cutie', 'coldplay', 'the killers'])
frozenset(['coldplay', 'red hot chili peppers', 'foo fighters'])
frozenset(['coldplay', 'franz ferdinand', 'the killers'])
frozenset(['placebo', 'coldplay', 'muse'])
frozenset(['coldplay', 'the killers', 'muse'])
frozenset(['nirvana', 'coldplay', 'red hot chili peppers'])
frozenset(['oasis', 'coldplay', 'radiohead'])
frozenset(['oasis', 'coldplay', 'the beatles'])
frozenset(['oasis', 'coldplay', 'the killers'])
frozenset(['radiohead', 'coldplay', 'sigur r\xc3\x83\xc2\xb3s'])
frozenset(['radiohead', 'coldplay', 'snow patrol'])
frozenset(['radiohead', 'coldplay', 'the killers'])
frozenset(['radiohead', 'the smashing pumpkins', 'coldplay'])
frozenset(['radiohead', 'coldplay', 'u2'])
frozenset(['coldplay', 'red hot chili peppers', 'the killers'])
frozenset(['coldplay', 'the killers', 'snow patrol'])
frozenset(['coldplay', 'the killers', 'the beatles'])
frozenset(['pink floyd', 'david bowie', 'the beatles'])
frozenset(['david bowie', 'the rolling stones', 'the beatles'])
frozenset(['death cab for cutie', 'radiohead', 'the shins'])
frozenset(['led zeppelin', 'pink floyd', 'radiohead'])
frozenset(['led zeppelin', 'pink floyd', 'the beatles'])
frozenset(['led zeppelin', 'pink floyd', 'the doors'])
frozenset(['led zeppelin', 'the rolling stones', 'the beatles'])
frozenset(['nirvana', 'metallica', 'red hot chili peppers'])
frozenset(['radiohead', 'placebo', 'muse'])
frozenset(['radiohead', 'the killers', 'muse'])
frozenset(['pink floyd', 'the beatles', 'the doors'])
frozenset(['radiohead', 'sigur r\xc3\x83\xc2\xb3s', 'the beatles'])
frozenset(['radiohead', 'the rolling stones', 'the beatles'])
frozenset(['radiohead', 'the beatles', 'the shins'])
frozenset(['radiohead', 'the smashing pumpkins', 'the beatles'])
frozenset(['the strokes', 'radiohead', 'the beatles'])

<u>Print Final Result with Support, Confidence, and Lift </u>

In [39]:
# print the rules, the support, the confidence, and lift for each rule
for item in association_results:
    # first index of the inner list
    # Contains base item and add item
    pair = item[0]
    items = [x for x in pair]
    print("Rule: With " + items[0] + " you can also listen " + items[1])

    # second index of the inner list
    print("Support: " + str(item[1]))

    # third index of the list located at 0th
    # of the third index of the inner list

    print("Confidence: " + str(item[2][0][2]))
    print("Lift: " + str(item[2][0][3]))
    print("=====================================")

Rule: With a perfect circle you can also listen tool
Support: 0.0162666666667
Confidence: 0.442831215971
Lift: 8.71714992069
=====================================
Rule: With arctic monkeys you can also listen kaiser chiefs
Support: 0.0125333333333
Confidence: 0.400852878465
Lift: 5.31165474998
=====================================
Rule: With rihanna you can also listen beyoncÃ©
Support: 0.0139333333333
Confidence: 0.468609865471
Lift: 10.881034028
=====================================
Rule: With black sabbath you can also listen metallica
Support: 0.0172
Confidence: 0.452631578947
Lift: 4.06555310432
=====================================
Rule: With sum 41 you can also listen blink-182
Support: 0.0141333333333
Confidence: 0.427419354839
Lift: 7.42047491039
=====================================
Rule: With breaking benjamin you can also listen linkin park
Support: 0.0108
Confidence: 0.44262295082
Lift: 4.50736202464
=====================================
Rule: With death cab for cutie you can also listen bright eyes
Support: 0.0152
Confidence: 0.402116402116
Lift: 4.94405412438
=====================================
Rule: With death cab for cutie you can also listen broken social scene
Support: 0.0114666666667
Confidence: 0.416464891041
Lift: 5.12046997182
=====================================
Rule: With radiohead you can also listen broken social scene
Support: 0.0150666666667
Confidence: 0.547215496368
Lift: 3.03558892216
=====================================
Rule: With children of bodom you can also listen in flames
Support: 0.013
Confidence: 0.401234567901
Lift: 8.1112109414
=====================================
Rule: With keane you can also listen coldplay
Support: 0.0222666666667
Confidence: 0.637404580153
Lift: 4.02063444167
=====================================
Rule: With coldplay you can also listen snow patrol
Support: 0.0264666666667
Confidence: 0.525132275132
Lift: 3.31244075988
=====================================
Rule: With coldplay you can also listen the fray
Support: 0.0112666666667
Confidence: 0.516819571865
Lift: 3.26000570983
=====================================
Rule: With travis you can also listen coldplay
Support: 0.0137333333333
Confidence: 0.562841530055
Lift: 3.55030401632
=====================================
Rule: With daft punk you can also listen justice
Support: 0.0145333333333
Confidence: 0.426614481409
Lift: 5.61334843959
=====================================
Rule: With death cab for cutie you can also listen the decemberists
Support: 0.0134666666667
Confidence: 0.423480083857
Lift: 5.20672234251
=====================================
Rule: With death cab for cutie you can also listen the postal service
Support: 0.0153333333333
Confidence: 0.469387755102
Lift: 5.77116092339
=====================================
Rule: With death cab for cutie you can also listen the shins
Support: 0.02
Confidence: 0.404858299595
Lift: 4.97776597863
=====================================
Rule: With led zeppelin you can also listen deep purple
Support: 0.0108666666667
Confidence: 0.402469135802
Lift: 5.08168100761
=====================================
Rule: With metallica you can also listen dream theater
Support: 0.0136666666667
Confidence: 0.412474849095
Lift: 3.70486391402
=====================================
Rule: With panic at the disco you can also listen fall out boy
Support: 0.0115333333333
Confidence: 0.434673366834
Lift: 8.41303290647
=====================================
Rule: With kaiser chiefs you can also listen franz ferdinand
Support: 0.0132
Confidence: 0.422174840085
Lift: 7.11530629357
=====================================
Rule: With linkin park you can also listen good charlotte
Support: 0.0101333333333
Confidence: 0.405333333333
Lift: 4.12763068568
=====================================
Rule: With guns n roses you can also listen metallica
Support: 0.0118666666667
Confidence: 0.419811320755
Lift: 3.77076036606
=====================================
Rule: With iron maiden you can also listen judas priest
Support: 0.0135333333333
Confidence: 0.5075
Lift: 8.56299212598
=====================================
Rule: With iron maiden you can also listen megadeth
Support: 0.0132666666667
Confidence: 0.430735930736
Lift: 7.26776036112
=====================================
Rule: With iron maiden you can also listen metallica
Support: 0.0296
Confidence: 0.499437570304
Lift: 4.48596620033
=====================================
Rule: With kanye west you can also listen jay-z
Support: 0.0150666666667
Confidence: 0.496703296703
Lift: 7.75291305988
=====================================
Rule: With nas you can also listen jay-z
Support: 0.0106
Confidence: 0.426273458445
Lift: 14.0529711575
=====================================
Rule: With led zeppelin you can also listen jimi hendrix
Support: 0.017
Confidence: 0.431472081218
Lift: 5.44787981336
=====================================
Rule: With metallica you can also listen judas priest
Support: 0.0131333333333
Confidence: 0.4925
Lift: 4.42365269461
=====================================
Rule: With kaiser chiefs you can also listen the killers
Support: 0.0150666666667
Confidence: 0.481876332623
Lift: 4.90709096357
=====================================
Rule: With nas you can also listen kanye west
Support: 0.0104
Confidence: 0.418230563003
Lift: 6.52805249224
=====================================
Rule: With kanye west you can also listen t.i.
Support: 0.0104
Confidence: 0.567272727273
Lift: 8.85441301674
=====================================
Rule: With keane you can also listen the killers
Support: 0.0140666666667
Confidence: 0.402671755725
Lift: 4.10052704404
=====================================
Rule: With koÐ¯n you can also listen system of a down
Support: 0.0214
Confidence: 0.434370771313
Lift: 4.77330517926
=====================================
Rule: With madonna you can also listen kylie minogue
Support: 0.0109333333333
Confidence: 0.478134110787
Lift: 8.7570349961
=====================================
Rule: With led zeppelin you can also listen pink floyd
Support: 0.032
Confidence: 0.40404040404
Lift: 3.85044857726
=====================================
Rule: With limp bizkit you can also listen linkin park
Support: 0.0128
Confidence: 0.450704225352
Lift: 4.58965606265
=====================================
Rule: With linkin park you can also listen papa roach
Support: 0.0131333333333
Confidence: 0.471291866029
Lift: 4.79930617137
=====================================
Rule: With metallica you can also listen megadeth
Support: 0.0162666666667
Confidence: 0.528138528139
Lift: 4.74375923478
=====================================
Rule: With motÃ¶rhead you can also listen metallica
Support: 0.0101333333333
Confidence: 0.429378531073
Lift: 3.85669339288
=====================================
Rule: With pantera you can also listen metallica
Support: 0.0124666666667
Confidence: 0.459459459459
Lift: 4.12688137239
=====================================
Rule: With slayer you can also listen metallica
Support: 0.0159333333333
Confidence: 0.474206349206
Lift: 4.25933846593
=====================================
Rule: With morrissey you can also listen the smiths
Support: 0.0112666666667
Confidence: 0.465564738292
Lift: 8.89614149603
=====================================
Rule: With sonata arctica you can also listen nightwish
Support: 0.0134666666667
Confidence: 0.510101010101
Lift: 8.23629187461
=====================================
Rule: With rihanna you can also listen the pussycat dolls
Support: 0.0104
Confidence: 0.577777777778
Lift: 13.4158926729
=====================================
Rule: With slipknot you can also listen system of a down
Support: 0.0185333333333
Confidence: 0.41124260355
Lift: 4.51914948956
=====================================
Rule: With arctic monkeys you can also listen coldplay
Support: 0.0116
Confidence: 0.427518427518
Lift: 3.74796984966
=====================================
Rule: With arctic monkeys you can also listen radiohead
Support: 0.0130666666667
Confidence: 0.488778054863
Lift: 3.08312482041
=====================================
Rule: With arctic monkeys you can also listen coldplay
Support: 0.0123333333333
Confidence: 0.454545454545
Lift: 4.62877244955
=====================================
Rule: With arctic monkeys you can also listen radiohead
Support: 0.011
Confidence: 0.411471321696
Lift: 3.60728803357
=====================================
Rule: With arctic monkeys you can also listen the killers
Support: 0.0110666666667
Confidence: 0.463687150838
Lift: 4.72186507982
=====================================
Rule: With beck you can also listen radiohead
Support: 0.013
Confidence: 0.590909090909
Lift: 3.27797202797
=====================================
Rule: With coldplay you can also listen the killers
Support: 0.0110666666667
Confidence: 0.48115942029
Lift: 4.89979043065
=====================================
Rule: With pink floyd you can also listen the beatles
Support: 0.0103333333333
Confidence: 0.615079365079
Lift: 3.45809238238
=====================================
Rule: With radiohead you can also listen the beatles
Support: 0.0138666666667
Confidence: 0.573002754821
Lift: 3.221529731
=====================================
Rule: With the rolling stones you can also listen the beatles
Support: 0.0114666666667
Confidence: 0.591065292096
Lift: 3.32308072768
=====================================
Rule: With death cab for cutie you can also listen coldplay
Support: 0.0108666666667
Confidence: 0.58844765343
Lift: 3.71182287697
=====================================
Rule: With coldplay you can also listen red hot chili peppers
Support: 0.0107333333333
Confidence: 0.453521126761
Lift: 3.8089680299
=====================================
Rule: With coldplay you can also listen franz ferdinand
Support: 0.0106
Confidence: 0.49226006192
Lift: 5.01283158777
=====================================
Rule: With placebo you can also listen coldplay
Support: 0.0112
Confidence: 0.47323943662
Lift: 4.14879693121
=====================================
Rule: With coldplay you can also listen the killers
Support: 0.0151333333333
Confidence: 0.508968609865
Lift: 3.21048324137
=====================================
Rule: With nirvana you can also listen coldplay
Support: 0.0104
Confidence: 0.444444444444
Lift: 3.73273609556
=====================================
Rule: With oasis you can also listen coldplay
Support: 0.0127333333333
Confidence: 0.587692307692
Lift: 3.70705829074
=====================================
Rule: With oasis you can also listen coldplay
Support: 0.0106
Confidence: 0.519607843137
Lift: 3.27759362786
=====================================
Rule: With oasis you can also listen coldplay
Support: 0.0111333333333
Confidence: 0.427109974425
Lift: 4.34938874159
=====================================
Rule: With radiohead you can also listen coldplay
Support: 0.0120666666667
Confidence: 0.580128205128
Lift: 3.21816681839
=====================================
Rule: With radiohead you can also listen coldplay
Support: 0.0100666666667
Confidence: 0.634453781513
Lift: 4.00202132998
=====================================
Rule: With radiohead you can also listen coldplay
Support: 0.0150666666667
Confidence: 0.524361948956
Lift: 3.30758167971
=====================================
Rule: With radiohead you can also listen the smashing pumpkins
Support: 0.0109333333333
Confidence: 0.628352490421
Lift: 3.48568319391
=====================================
Rule: With radiohead you can also listen coldplay
Support: 0.0114
Confidence: 0.521341463415
Lift: 3.28852899547
=====================================
Rule: With coldplay you can also listen red hot chili peppers
Support: 0.0108666666667
Confidence: 0.509375
Lift: 3.21304667788
=====================================
Rule: With coldplay you can also listen the killers
Support: 0.0104
Confidence: 0.595419847328
Lift: 3.75580223294
=====================================
Rule: With coldplay you can also listen the killers
Support: 0.0125333333333
Confidence: 0.534090909091
Lift: 3.36895022555
=====================================
Rule: With pink floyd you can also listen david bowie
Support: 0.0100666666667
Confidence: 0.574144486692
Lift: 3.22794876326
=====================================
Rule: With david bowie you can also listen the rolling stones
Support: 0.01
Confidence: 0.570342205323
Lift: 3.20657161913
=====================================
Rule: With death cab for cutie you can also listen radiohead
Support: 0.0100666666667
Confidence: 0.444117647059
Lift: 5.46046287367
=====================================
Rule: With led zeppelin you can also listen pink floyd
Support: 0.0112
Confidence: 0.452830188679
Lift: 4.31540840546
=====================================
Rule: With led zeppelin you can also listen pink floyd
Support: 0.0156
Confidence: 0.466135458167
Lift: 4.44220576398
=====================================
Rule: With led zeppelin you can also listen pink floyd
Support: 0.0106666666667
Confidence: 0.597014925373
Lift: 5.68946879326
=====================================
Rule: With led zeppelin you can also listen the rolling stones
Support: 0.0106666666667
Confidence: 0.57761732852
Lift: 3.24747373606
=====================================
Rule: With nirvana you can also listen metallica
Support: 0.0104
Confidence: 0.411609498681
Lift: 3.45696667425
=====================================
Rule: With radiohead you can also listen placebo
Support: 0.0136666666667
Confidence: 0.513784461153
Lift: 4.50424717551
=====================================
Rule: With radiohead you can also listen the killers
Support: 0.0128
Confidence: 0.445475638051
Lift: 3.90539717754
=====================================
Rule: With pink floyd you can also listen the beatles
Support: 0.01
Confidence: 0.42735042735
Lift: 4.07258984133
=====================================
Rule: With radiohead you can also listen sigur rÃ³s
Support: 0.0104666666667
Confidence: 0.643442622951
Lift: 3.56939324862
=====================================
Rule: With radiohead you can also listen the rolling stones
Support: 0.0106
Confidence: 0.563829787234
Lift: 3.1699575744
=====================================
Rule: With radiohead you can also listen the beatles
Support: 0.0106666666667
Confidence: 0.567375886525
Lift: 3.14742540602
=====================================
Rule: With radiohead you can also listen the smashing pumpkins
Support: 0.0114666666667
Confidence: 0.620938628159
Lift: 3.4445559994
=====================================
Rule: With the strokes you can also listen radiohead
Support: 0.0104666666667
Confidence: 0.560714285714
Lift: 3.11047125951
=====================================